// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function LoadSaves() {
  return window['go']['main']['App']['LoadSaves']();
}

export function PushToHistory(arg1) {
  return window['go']['main']['App']['PushToHistory'](arg1);
}

export function PushToSaved(arg1) {
  return window['go']['main']['App']['PushToSaved'](arg1);
}

export function RemoveFromSaved(arg1) {
  return window['go']['main']['App']['RemoveFromSaved'](arg1);
}

export function SaveHistory() {
  return window['go']['main']['App']['SaveHistory']();
}
