// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadHistory():Promise<string>;

export function LoadSaves():Promise<string>;

export function PushToHistory(arg1:string):Promise<void>;

export function PushToSaved(arg1:string):Promise<void>;

export function RemoveFromSaved(arg1:string):Promise<void>;

export function SaveHistory():Promise<void>;
